apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sredevopsweb-pvc
  namespace: sredevops-web
spec:
  accessModes:
  - ReadWriteOnce # or ReadWriteMany, if you want to use NFS or 
  resources:
    requests:
      storage: 10Gi # Or anything above 1Gi and whatever you need to store with Ghost.      
  storageClassName: local-path # or another, depending on your provider, this is for k3s
