apiVersion: v1
kind: Service
metadata:
  name: sredevopsweb
  namespace: sredevops-web
  labels:
    app: sredevopsweb
spec:
  ports:
  - port: 2368
    protocol: TCP
    targetPort: 2368
    name: sredevopsweb
  type: ClusterIP
  selector:
    app: sredevopsweb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sredevopsweb
  namespace: sredevops-web
spec:
  tls:
  - hosts:
    - sredevops.cl
    - www.sredevops.cl
    secretName: sredevops-cl-tls
  rules:
  - host: sredevops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: sredevopsweb
            port:
              number: 2368
  - host: www.sredevops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: sredevopsweb
            port:
              number: 2368
