apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ghost-on-kubernetes.fullname" . }}
      {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}

type: Opaque
data:
  MYSQL_DATABASE: {{ .Values.mysqlStatefulset.database | toString }}
  MYSQL_PASSWORD: {{ .Values.mysqlStatefulset.password | toString }}
  MYSQL_USER: {{ .Values.mysqlStatefulset.user | toString }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysqlStatefulset.rootPassword | toString }}
  MYSQL_PORT: {{ .Values.mysqlStatefulset.port | toString | quote}}
  
