apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ghost-on-kubernetes.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "ghost-on-kubernetes.labels" . | nindent 4 }}
data:
  config.production.json: {{- include "ghost-on-kubernetes.configProductionJson" . | toJson | b64enc | nindent 4 }}
type: Opaque
