apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghostk3s-static-ghost
  namespace: ghostk3s
  labels:
    app: ghostk3s
spec:
  storageClassName: default
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
