apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghostk3s-static-ghost
  namespace: ghostk3s
  labels:
    app: ghostk3s
spec:
  storageClassName: default # Change this to your storageClassName
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce # Change this to your accessModes
  resources:
    requests:
      storage: 5Gi
