apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghostk3s-static-ghost
  namespace: ghostk3s
  labels:
    app: ghostk3s
spec:
  storageClassName: "longhorn-rwx"
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
