apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: ghost-on-kubernetes
  labels:
    app: ghost-on-kubernetes
spec:
  ports:
  - port: 2368
    protocol: TCP
    targetPort: 2368
    name: ghost-service
  type: ClusterIP
  selector:
    app: ghost-on-kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ghost-on-kubernetes
  namespace: ghost-on-kubernetes
  labels:
    app: mysql-ghost-on-kubernetes
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql-ghost-on-kubernetes
  type: ClusterIP
  clusterIP: None
  selector:
    app: mysql-ghost-on-kubernetes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost-on-kubernetes
  namespace: ghost-on-kubernetes
spec:
  tls:
  - hosts:
    - ghost-on-kubernetes.local
    secretName: ghost-on-kubernetes-tls
  rules:
  - host: ghost-on-kubernetes.local
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ghost-service
            port:
              number: 2368
