apiVersion: v1
kind: Service
metadata:
  name: sredevops-svc
  namespace: sredevops
  labels:
    app: sredevops
spec:
  ports:
  - port: 2368
    protocol: TCP
    targetPort: 2368
    name: sredevops
  type: ClusterIP
  selector:
    app: sredevops
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-sredevops
  namespace: sredevops
  labels:
    app: mysql-sredevops
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql-sredevops
  type: ClusterIP
  clusterIP: None
  selector:
    app: mysql-sredevops
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sredevops
  namespace: sredevops
spec:
  tls:
  - hosts:
    - sredevops.cl
    secretName: sredevops-cl-tls
  rules:
  - host: sredevops.cl
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: sredevops-svc
            port:
              number: 2368
