apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sredevops
  namespace: sredevops
  labels:
    app: mysql-sredevops
spec:
  serviceName: mysql-sredevops
  replicas: 1
  selector:
    matchLabels:
      app: mysql-sredevops
  template:
    metadata:
      labels:
        app: mysql-sredevops
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: mysql-sredevops
          securityContext:
          #   capabilities:
          #     drop:
          #       - all
          #     add:
          #       - CHOWN
          #       - DAC_OVERRIDE
          #       - SETGID
          #       - SETUID
          #       - SETPCAP
          #       - NET_BIND_SERVICE
          #   readOnlyRootFilesystem: true
          #   runAsUser: 10001
          #   runAsGroup: 1001
            allowPrivilegeEscalation: false
            
          image: docker.io/mysql/mysql-server:8.0.32-1.2.11-server
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: mysql-sredevops
          resources:
            requests:
              memory: 0Mi
              cpu: 0m
            limits:
              memory: 512Mi
              cpu: 500m
          ports:
            - containerPort: 3306
              protocol: TCP
          # livenessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - mysqladmin ping -h 
          #       - localhost
          #       - -u 
          #       - root
          #       - -p
          #       - $MYSQL_ROOT_PASSWORD
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          # readinessProbe:
          #   exec:
          #     command:
          #       - sh
          #       - -c
          #       - mysqladmin ping -h 
          #       - localhost
          #       - -u 
          #       - root
          #       - -p
          #       - $MYSQL_ROOT_PASSWORD
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   timeoutSeconds: 5
            
          volumeMounts:
            - name: mysql-sredevops-pvc
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-sredevops-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
      storageClassName: local-path
      volumeMode: Filesystem

