apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ghost-on-kubernetes
  namespace: ghost-on-kubernetes
spec:
  selector:
    matchLabels:
      app: ghost-on-kubernetes
  serviceName: "ghost-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost-on-kubernetes
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: ghost-on-kubernetes
        image: ghcr.io/sredevopsdev/ghost-on-kubernetes:main
        resources:
          requests:
            memory: 0Mi
            cpu: 0m
          limits:
            memory: 1Gi
            cpu: 1000m
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - CHOWN
              - DAC_OVERRIDE
              - SETGID
              - SETUID
              - SETPCAP
              - NET_BIND_SERVICE
          runAsUser: 10001
          runAsGroup: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

        ports:
        - containerPort: 2368
          name: ghost-on-kubernetes
          protocol: TCP
        env:
          - name: NODE_ENV
            value: production
        volumeMounts:
          - name: ghost-on-kubernetes-volume
            mountPath: /var/lib/ghost/content
          - name:  ghost-config-prod
            mountPath: /var/lib/ghost/config.production.json
            subPath: config.production.json
            readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 2368
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 30
          failureThreshold: 3
      volumes:
      - name: ghost-on-kubernetes-volume
        persistentVolumeClaim:
          claimName: ghost-pvc
      - name: ghost-config-prod
        secret:
          secretName: ghost-config-prod

