apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-k8s
  namespace: ghost-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-k8s
      app.kubernetes.io/name: ghost-k8s
      app.kubernetes.io/instance: ghost-k8s
      app.kubernetes.io/version: "5.8"
      app.kubernetes.io/component: frontend
      app.kubernetes.io/part-of: ghost-k8s
  template:
    metadata:
      namespace: ghost-k8s
      labels:
        app: ghost-k8s
        app.kubernetes.io/name: ghost-k8s
        app.kubernetes.io/instance: ghost-k8s
        app.kubernetes.io/version: "5.8"
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: ghost-k8s
    spec:
      automountServiceAccountToken: false # Disable automounting of service account token
      volumes:
      - name: ghost-k8s-static-ghost
        persistentVolumeClaim:
          claimName: ghost-k8s-static-ghost

      - name: ghost-config-prod
        secret:
          secretName: ghost-config-prod
          defaultMode: 420

      - name: tmp
        emptyDir:
          sizeLimit: 64Mi

      initContainers:
      - name: ghost-k8s-init
        image: docker.io/bitnami/git:2
        env:
        - name: GHOST_INSTALL
          value: /var/lib/ghost
        - name: GHOST_CONTENT
          value: /var/lib/ghost/content
        - name: NODE_ENV
          value: production
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          # runAsNonRoot: true
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        command:
        - /bin/bash
        - -c
        - |
          set -ex
          # Check if $GHOST_CONTENT/themes/source exists, if it doesn't exist clone it and then set the ownership
          if [ ! -d "$GHOST_CONTENT/themes/source" ]; then
            git clone https://github.com/TryGhost/Source $GHOST_CONTENT/themes/source --single-branch --branch=main --depth=1
            chown -R 1000:1000 $GHOST_CONTENT/themes/source
            echo "Cloned Source theme"
          else
            echo "Source theme already exists"
          fi
          # Check if $GHOST_CONTENT/themes/casper exists, if it doesn't exist clone it and then set the ownership
          if [ ! -d "$GHOST_CONTENT/themes/casper" ]; then
            git clone https://github.com/TryGhost/Casper $GHOST_CONTENT/themes/casper --single-branch --branch=main --depth=1
            chown -R 1000:1000 $GHOST_CONTENT/themes/casper
            echo "Cloned Casper theme"
          else
            echo "Casper theme already exists"
          fi
          # Assure ownership of the ghost installation for the user node
          chown -R 1000:1000 $GHOST_CONTENT
          echo "Assured ownership of the ghost installation"
          exit 0

        volumeMounts:
        - name: ghost-k8s-static-ghost
          mountPath: /var/lib/ghost/content
          readOnly: false

      containers:
      - name: ghost-k8s
        image: ghcr.io/sredevopsorg/ghost-on-kubernetes:distroless
        imagePullPolicy: Always
        ports:
        - name: ghk3s
          containerPort: 2368
          protocol: TCP

        # readinessProbe:
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        #   timeoutSeconds: 3
        #   successThreshold: 1
        #   failureThreshold: 6
        #   httpGet:
        #     path: /ghost/api/v4/admin/site/
        #     port: ghk3s
        #     httpHeaders:
        #     - name: X-Forwarded-Proto
        #       value: https
        #     - name: Host
        #       value: tests.yourdomain.com
        # livenessProbe:
        #   httpGet:
        #     path: /ghost/api/v4/admin/site/
        #     port: ghk3s
        #     httpHeaders:
        #     - name: X-Forwarded-Proto
        #       value: https
        #     - name: Host
        #       value: tests.yourdomain.com
        #   periodSeconds: 3600
        #   timeoutSeconds: 3
        #   successThreshold: 1
        #   failureThreshold: 1
        #   initialDelaySeconds: 60

        env:
        - name: NODE_ENV
          value: production
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 100Mi

        volumeMounts:
        - name: ghost-k8s-static-ghost
          mountPath: /var/lib/ghost/content
        - name: ghost-config-prod
          readOnly: true
          mountPath: /var/lib/ghost/config.production.json
          subPath: config.production.json
        - name: tmp # This is the temporary volume mount to allow loading themes
          mountPath: /tmp
          readOnly: false
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000

      restartPolicy: Always
      terminationGracePeriodSeconds: 15
      dnsPolicy: ClusterFirst
      # Optional: Uncomment the following to specify node selectors
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: static
      #               operator: In
      #               values:
      #                 - "true"


      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 600
