name: Build and push image to DockerHub and GitHub Container Registry

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      manual-tag:
        description: 'Manual Tag'
        required: true
        default: 'main'
        type: string
      ghost_version:
        description: 'Ghost version'
        required: true
        default: '5.54.0'
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ secrets.DOCKER_USER }}/${{ github.event.repository.name }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=req,event=tag
            type=raw,value=${{ github.event.inputs.manual-tag }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.title=ghost-on-kubernetes
            org.opencontainers.image.description=Ghost CMS upstream v${{ github.event.inputs.ghost_version }} , with node:18-bookworm and 
            org.opencontainers.image.vendor=SREDevOps.cl
            org.opencontainers.image.source=https://github.com/sredevopsdev/ghost-on-kubernetes
            org.opencontainers.image.documentation=https://github.com/sredevopsdev/ghost-on-kubernetes
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            GHOST_VERSION=${{ github.event.inputs.ghost_version }}
