name: Build with kaniko container

on:
  push:
    branches:
      - kaniko
  # push:
  #   tags:
  #     - 'v*'
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      manual-tag:
        description: 'Manual Tag'
        required: false
        default: 'main'
        type: string
      ghost_version:
        description: 'Ghost version'
        required: false
        default: '5.80.2'
        type: string

permissions:
  contents: read
  packages: write
  id-token: write # needed for signing the images with GitHub OIDC Token

jobs:
  kaniko:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ vars.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      GITHUB_USER: ${{ github.actor }}
      GITHUB_TOKEN: ${{ github.token }}
      PROJECT: ${{ github.repository_owner }}

    container:
      image: gcr.io/kaniko-project/executor:debug
      options: --entrypoint ["dockerfile=<path to Dockerfile within the build context>", "context=dir://<path to build context>", "destination=<gcr.io/$PROJECT/$IMAGE:$TAG>"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Workdir
        run: |
          cp ./Dockerfile /workspace/Dockerfile
        working-directory: ${{ github.workspace }}

      - name: Credentials as docker config
        run: |
          echo "{\"auths\":{\"docker.pkg.github.com\":{\"username\":\"${DOCKER_USER}\",\"password\":\"${DOCKER_PASS}\"},\"ghcr.io\":{\"username\":\"${GITHUB_USER}\",\"password\":\"${GITHUB_TOKEN}\"}}}" > /kaniko/.docker/config.json
        working-directory: /workspace
