name: Delete old container images

on:
  workflow_dispatch:

permissions:
  packages: write
  repository-projects: read
  contents: read
  actions: read
  id-token: write


jobs:
  clean-ghcr:
    name: Delete old unused container images
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Delete 'ghost-on-kubernetes' containers older than a week
        uses: sredevopsorg/container-retention-policy@v2
        with:
          image-names: ghost-on-kubernetes
          cut-off: A week ago UTC
          account-type: org
          org-name: sredevopsorg
          keep-at-least: 3
          untagged-only: false
          token-type: github-token
          token: ${{ github.token }}
          skip-tags: main

      - name: Delete all test containers older than a month, using a wildcard
        uses: sredevopsorg/container-retention-policy@v2
        with:
          image-names: ghost-on-kubernetes
          cut-off: One month ago UTC
          account-type: org
          org-name: sredevopsorg
          keep-at-least: 3
          skip-tags: main
          untagged-only: false
          token-type: github-token
          token: ${{ github.token }}
